name = "fileopener-redirect"
main = "src/index.js"
compatibility_date = "2024-09-14"

# Optional: Configure custom domain route when you have a domain
# [[routes]]
# pattern = "your-domain.com/*"
# zone_name = "your-domain.com"



[env.development]
name = "fileopener-redirect"
workers_dev = true

# Optional: Add KV storage if you need to store data
# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "your-kv-namespace-id"