name = "fopen-redirect"
main = "src/index.js"
compatibility_date = "2024-09-14"

# Optional: Configure custom domain route when you have a domain
# [[routes]]
# pattern = "your-domain.com/*"
# zone_name = "your-domain.com"

[env.production]
name = "fopen-redirect-prod"

[env.development]
name = "fopen-redirect-dev"